spring:
  application:
    name: xjp-stock
  profiles:
    active: dev
server:
  port: 8081

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志输出
#  mapper-locations: classpath*:mapper/*.xml # mapper文件的位置
#  type-aliases-package: org.xjp.xjpstock.business.entity # 实体类的包路径